### ISSUE TITLE
Add information for using infnoise with udev

### ISSUE THREAD

**Issue by AbigailBuccaneer** [waywardgeek/infnoise#12]
`software/README` talks about running as a daemon, and using `rngd` to add entropy from a FIFO to `/dev/random`. However, it's possible to use `udev` to start the daemon whenever the infnoise is plugged in, as so:

```
$ cat /etc/udev/rules.d/75-infnoise.rules
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", RUN+="/usr/local/bin/infnoise --dev-random --daemon"
```

Many similar software packages for hardware will ship udev rules in the repository with instructions on how to add the rules and check that they're working. I think this would be useful for infnoise, as it provides the lowest-friction way to use the infnoise.

If you think this would be useful in the repository, I can make a pull request with a rules file and instructions on how to use it (and maybe even `make` rules to install infnoise and the rules).

**Comment by waywardgeek** [comment]
Thanks, Abigail!  I added your udev file at the end of the README to
start.  Maybe it makes sense to have it as a make option.  My only
hesitation is that even this super-simple Makefile is already not portable
across Linux distros (it does not work on Fedora, for example).  I prefer
not to include distro-specific stuff.

Thanks,
Bill

**Comment by letoff** [comment]
Hi there,

I have some problems running infnoise with this method. When I run it from the command line everything runs smoothly and I can generate random nums for hours with gpg. 
But when the same command (i.e /usr/local/bin/infnoise --dev-random --daemon) is executed by the udev rule above it crash after a while (generally a few seconds).

Here is what strace says:

`select(5, NULL, [4], NULL, {0, 1000})   = 1 (out [4], left {0, 982})
ioctl(4, USBDEVFS_REAPURBNDELAY, 0x7fff171a38f8) = 0
ioctl(4, USBDEVFS_SUBMITURB, 0x7fff171a3930) = 0
ioctl(4, USBDEVFS_REAPURBNDELAY, 0x7fff171a38f8) = -1 EAGAIN (Resource temporarily unavailable)
select(5, NULL, [4], NULL, {0, 1000})   = 1 (out [4], left {0, 993})
ioctl(4, USBDEVFS_REAPURBNDELAY, 0x7fff171a38f8) = 0
ioctl(3, RNDGETENTCNT, 0x7fff171a3a8c)  = 0
poll([{fd=3, events=POLLOUT}], 1, 1000) = 0 (Timeout)
ioctl(3, RNDADDENTROPY, 0x11b9010)      = 0
ioctl(4, USBDEVFS_SUBMITURB, 0x7fff171a3960) = -1 EBUSY (Device or resource busy)
write(2, "USB write failed\n", 17)      = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=2527, si_uid=0} ---
exit_group(-1)                          = ?
+++ exited with 255 +++
`
So I guess it has something to do with ftdi_write_data. Any idea why it works fine when executed  from command line and not from udev rule ?

**Comment by letoff** [comment]
And BTW there seems to be a zombie process just after plugin-in the device:

asusport ~ # ps faux|grep infnoise
root      1002  0.0  0.0      0     0 ?        Z    16:43   0:00      \_ [infnoise] <defunct>
root      1005  0.0  0.0  12748  2192 pts/1    S+   16:43   0:00  |           \_ grep infnoise
root      1003  0.5  0.0  16024  2088 ?        S    16:43   0:00 /usr/local/bin/infnoise --dev-random --daemon

**Comment by mrplumber** [comment]
Hello,

This method doe's not work on Debian Jessie.

Here is relevant dmesg output on device insertion:

[83350.556035] usb 2-4: new full-speed USB device number 18 using ohci-pci
[83350.787052] usb 2-4: New USB device found, idVendor=0403, idProduct=6015
[83350.792483] usb 2-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[83350.797963] usb 2-4: Product: FT240X USB FIFO
[83350.803363] usb 2-4: Manufacturer: FTDI
[83350.808681] usb 2-4: SerialNumber: DN004WRD
[83350.822111] ftdi_sio 2-4:1.0: FTDI USB Serial Device converter detected
[83350.828454] usb 2-4: Detected FT-X
[83350.833961] usb 2-4: Number of endpoints 2
[83350.839446] usb 2-4: Endpoint 1 MaxPacketSize 64
[83350.844883] usb 2-4: Endpoint 2 MaxPacketSize 64
[83350.850146] usb 2-4: Setting MaxPacketSize 64
[83350.863116] usb 2-4: FTDI USB Serial Device converter now attached to ttyUSB0
[83351.068409] ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
[83351.074254] ftdi_sio 2-4:1.0: device disconnected
[83382.640061] usb 2-4: usbfs: process 6260 (infnoise) did not claim interface 0 before use

Here is relevant journalctl output:

<...> same as above <...>
Aug 17 16:17:33 homeserv kernel: ftdi_sio ttyUSB0: FTDI USB Serial Device converter now disconnected from ttyUSB0
Aug 17 16:17:33 homeserv kernel: ftdi_sio 2-4:1.0: device disconnected
Aug 17 16:18:03 homeserv systemd-udevd[6258]: timeout '/usr/local/bin/infnoise --dev-random --daemon'
Aug 17 16:18:04 homeserv kernel: usb 2-4: usbfs: process 6260 (infnoise) did not claim interface 0 before use
Aug 17 16:18:34 homeserv systemd-udevd[6258]: timeout '/usr/local/bin/infnoise --dev-random --daemon'

If started by user from console runs as expected.

**Comment by manuel-domke** [comment]
Actually, using udev for this is not the right way, as we want to start a daemon which is not the idea of udev.

Thats why all the problems arise..
Jul 25 17:57:23 zen systemd-udevd[616]: seq 3118 '/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0' is taking a long time
Jul 25 17:59:23 zen systemd-udevd[616]: seq 3118 '/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0' killed

I'm gonna try to write a systemd device unit, which will hopefully do the job.

**Comment by waywardgeek** [comment]
Is everything working OK with udev now?  If so, I'll close this issue.
