### ISSUE TITLE
Init scripts

### ISSUE THREAD

**Issue by captainpete** [waywardgeek/infnoise#17]
Here's one for Gentoo
https://gist.github.com/captainpete/b5b6f2d19abae2e88f14

and one for use with upstart (Ubuntu)
https://gist.github.com/captainpete/19dab1f0dd37e7d5d8db

Would be nice to have one for systemd, still haven't written it yet.
Useful to include these?

**Comment by waywardgeek** [comment]
Would you mind putting init scripts in a directory under software, perhaps "init_scripts"?  I'll merge a pull request if you send one.

**Comment by captainpete** [comment]
Awesome, thanks!
