### ISSUE TITLE
infnoise won't run without increased privileges

### ISSUE THREAD

**Issue by scruss** [waywardgeek/infnoise#2]
Any way to make infnoise run as a regular user without sudo? The less we need sudo, the better.

**Comment by waywardgeek** [comment]
Yes.  In Ubuntu, add some access rules in udev, and add the user to a
group.  I'll document this this week

**Comment by maztaim** [comment]
There are ways to do this.  here is what I did.

Add a group called infnoise.  Add the user you want to see the device to the infnoise group.

```
$ sudo groupadd infnoise
$ sudo usermod -a -G infnoise myid
```

Create a udev rule.

```
$ sudo vi /etc/udev/rules.d/70-infnoise.rules
SUBSYSTEMS=="usb", ATTRS{product}=="Infinite Noise TRNG", GROUP="infnoise"
```
Restart udevd.  On Fedora, I think you can get away with this by running the following.

```
$ sudo systemctl restart systemd-udevd
```

Frankly, I cheated and just rebooted.

**Comment by waywardgeek** [comment]
I think the udev rules work OK now.  Please re-open if there are still issues.
