### ISSUE TITLE
Sample dieharder output?

### ISSUE THREAD

**Issue by proegssilb** [waywardgeek/infnoise#42]
I came here from the Crowd Supply campaign, and was wondering if you felt comfortable (or that it was a wise idea) to post some of the results you've seen from dieharder. It'd be even cooler if they were generated by a CI server, but having any results at all would be nice.

**Comment by waywardgeek** [comment]
It "passed" Dieharder long ago.  There's a web-site that has results from
many devices, but I'm not able to find it at the moment.

**Comment by manuel-domke** [comment]
I'm working on a testsuite for the Infinite Noise, to be integrated into the CI server for building the linux packages. 
You can find the current work in progress here: https://files.13-37.org/tests
(dieharder tests are still running)

The test results will be examined in detail during the crowdsupply campaign - so stay tuned!

**Comment by proegssilb** [comment]
Very promising! Any chance those results can be linked to from a readme somewhere?

I think with a clear answer to that, we can close this out.

**Comment by manuel-domke** [comment]
Yes, I'll commit results for some longer-run tests when they're done. 
Just leave the issue open until then.

**Comment by manuel-domke** [comment]
uploaded them here a while ago: https://github.com/waywardgeek/infnoise/tree/master/tests/results_250000K
