### ISSUE TITLE
Linux kernel driver for in-kernel users of infnoise

### ISSUE THREAD

**Issue by sbates130272** [waywardgeek/infnoise#50]
Great project! Has anyone looked at an in-kernel version of infnoise to provide TRNG services to other parts of the kernel? It could also expose the infnoise devices in the device tree to make consumption by user-space easier?

**Comment by sbates130272** [comment]
Perhaps modelled on something that already exists in the kernel like:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/usb/misc/chaoskey.c?h=v4.16

**Comment by manuel-domke** [comment]
Also thought about this, but its probably a long road to go and I'm not so sure if whitening has its place in a kernel driver.

Anyway, the Infinite Noise TRNG driver can feed the kernels entropy pool so other "parts" can access its entropy.
Or am I wrong? Is there a downside of the current approach I'm not aware of?

I think we should stick to the libinfnoise idea (#51) for integration in custom applications and infnoise for use with shell scripts or /dev/random mode. (for now)

Based on the lib it will be a lot easier to implement a kernel driver.
