### ISSUE TITLE
libinfnoise

### ISSUE THREAD

**Issue by sbates130272** [waywardgeek/infnoise#51]
Hi

Awesome project ;-). Right now infnoise compiles as a executable. Could we develop a libinfnoise target for both windows and Linux so it's easier for people to pull the TRNG streams into their user-space applications?

Stephen

**Comment by manuel-domke** [comment]
I've worked on the interface, see  

```
bool listUSBDevices(struct ftdi_context *ftdic, struct inm_devlist **result, char **message);

bool initInfnoise(struct ftdi_context *ftdic, char *serial, bool debug);

bool initKeccak(struct ftdi_context *ftdic, char *serial);

uint64_t readRawData(struct ftdi_context *ftdic, uint8_t *result);

uint64_t readData(struct ftdi_context *ftdic, uint8_t *keccakState, uint8_t *result, uint32_t outputMultiplier);

```

The infnoise binary still has dependancies to libinfnoise_private.h, which are really hard to avoid without duplicating lots of code - but I think its pretty OK this way.

Still some stuff to clean up and fix - but this could become a release candidate soon.

**Comment by manuel-domke** [comment]
I created pull request #55 for the current state of work.

libinfnoise is usable for now, but the interface may change. Feedback wanted!

**Comment by manuel-domke** [comment]
I've opened another fork for furt libinfnoise developments.

My next goal is to fully separate input and output, so libinfnoise can be used independently.

https://github.com/13-37-org/infnoise/tree/libinfnoise/software

**Comment by manuel-domke** [comment]
IMO the refactoring is done. This is how the interface finally looks: 

    // initialize device
    bool initInfnoise(struct infnoise_context *context, char *serial, bool keccak, bool debug);

    // reads data in chunks of 32-128KB, depending in multiplier
    uint32_t readData(struct infnoise_context *context, uint8_t *result, bool raw, uint32_t outputMultiplier);

    // returns a struct listing the connected (FTDI) devices.
    devlist_node listUSBDevices(char **message);
