### ISSUE TITLE
make install of software fails when installing udev rules and startup service

### ISSUE THREAD

**Issue by jdimpson** [waywardgeek/infnoise#52]
https://github.com/waywardgeek/infnoise/blob/fc0d99f58fff60b5cb7dca583f4bbcc60e1f63a2/software/Makefile#L33

The install rule of the software Makefile tries to install 75-infnoise.rules file from the infnoise/software directory, but that file is actually in infnoise/software/init_scripts. Same problem for infnoise.service

To fix, I edited the Makefile to provide the correct path to the files. 

Thanks!

**Comment by manuel-domke** [comment]
Thanks! Fixed in #54
