### ISSUE TITLE
OSX instructions or binaries?

### ISSUE THREAD

**Issue by rorobaba** [waywardgeek/infnoise#64]
How would one run the device on OSX?

**Comment by manuel-domke** [comment]
Hi,

please check these issues/pull requests for the current state of work:

- "FreeBSD and macOS support": https://github.com/13-37-org/infnoise/issues/8
- "Fixed macOS build, documentation tweaks": https://github.com/manuel-domke/infnoise/pull/3

The already merged request's README including a section on how to compile on Mac:
https://github.com/manuel-domke/infnoise/blob/master/software/README.md

I'm working on getting all the required to this repo, but there is a lot of stuff coming together (libinfnoise refactoring (#51), cmake (https://github.com/13-37-org/infnoise/tree/cmake))

**Comment by manuel-domke** [comment]
Now merged everything I'm aware of. If something is still missing / not working, please let me know.

Just got my first Mac(Book) so I can start learning how to use it (and compile infnoise..). So hopefully I can test on Mac by myself soon!
