### ISSUE TITLE
Windows driver generates extra 0D characters

### ISSUE THREAD

**Issue by jironpech** [waywardgeek/infnoise#8]
The windows driver unhelpfully appends a hex 0D "character" to every instance of an 0A in the file it writes to make the familiar 0D 0A. This is a typical problem with text files shared between Linux and Windows, but the file should be defined as a binary type so this does not happen. A simple analysis of the file using HxD shows that the 0D bytes are twice as common as everything else. This ruins the entropy, of course.

![image](https://cloud.githubusercontent.com/assets/13809344/9288771/33f01746-4359-11e5-9b94-a9fdbace265f.png)

**Comment by waywardgeek** [comment]
Well, crips!  I thought that bug was put to rest ages ago.  It probably
re-occurred when I pulled a Windows update.  The latest way to open the
output file is:

outFile = _fsopen(argv[xArg], "w", _SH_DENYWR);

Should it be "wb"?

Thanks for catching this!
Bill

**Comment by jironpech** [comment]
OK, that narrows it down a lot - I'll play with that line.

**Comment by waywardgeek** [comment]
Thanks!  I have limited access to Windows machines currently, so if you can
verify a fix, that would help a lot.

Bill

**Comment by jironpech** [comment]
Verified - "wb" fixes the output, so thanks for the tip. I can contribute a compiled binary and a few details in the documentation if that helps.

**Comment by waywardgeek** [comment]
Actually, it would, if you don't mind :)

**Comment by jironpech** [comment]
OK, I created a branch that fixes the 0D error. I also fixed some pathname problems in the VS solution. The latest "daemon" updates broke the windows build. This line in infnoise.h is the culprit:
int writePid(pid_t pid, char *fileName);

I don't know if the daemon is intended for the windows version; it sounds like it might be an OS specific tweak. Anyway, the windows and linux versions may not be able to share a header file anymore unless this line can be moved somewhere else or the daemon function can be ported to windows. 

As a quick fix I established a new header file for the windows build that omits this line.

I'm not sure how this "pull request" stuff works. What's the best way to review and incorporate these changes?

**Comment by waywardgeek** [comment]
On Sun, Aug 23, 2015 at 3:24 AM, jironpech <notifications@github.com> wrote:

> OK, I created a branch that fixes the 0D error. I also fixed some pathname
> problems in the VS solution. The latest "daemon" updates broke the windows
> build. This line in infnoise.h is the culprit:
> int writePid(pid_t pid, char *fileName);
>
> I don't know if the daemon is intended for the windows version; it sounds
> like it might be an OS specific tweak. Anyway, the windows and linux
> versions may not be able to share a header file anymore unless this line
> can be moved somewhere else or the daemon function can be ported to windows.
>
This was a bug.  I changed that declaration to make it portable.

> As a quick fix I established a new header file for the windows build that
> omits this line.
>
> I'm not sure how this "pull request" stuff works. What's the best way to
> review and incorporate these changes?
>
I merged your changes, and switched back to using infnoise.h.  If you get a
chance, it would be great if you could test that the merged version
compiles in Windows.  I manually edited a couple vcproj files where
infnoise_win.h occurred, and changed them to infnoise.h, and I am not sure
I got it right.

Thanks for the patch!

Bill

**Comment by jironpech** [comment]
The windows version compiles perfectly - issue closed! Nice teamwork...

**Comment by waywardgeek** [comment]
Thanks for helping out!
