### ISSUE TITLE
FTDI chip & code injection

### ISSUE THREAD

**Issue by alphazo** [waywardgeek/infnoise#9]
The FTDI chip USB/UART interface is a microcontroller and its firmware can be updated over USB. Could that not be a threat so when you plug the dongle in a rogue computer, it changes the FTDI firmware so it manipulates the raw random data stream before sending it over to the host computer?

**Comment by waywardgeek** [comment]
Is the firmware upgradeable?  I have not seen this capability in the API
docs.

**Comment by alphazo** [comment]
Sorry I think I may have a looked at the wrong FTDI part number. The one used in this design seems to only have provision for re-programming USB configuration descriptors via FT_PROG and not the whole firmware.

**Comment by waywardgeek** [comment]
Honestly, a concern I still have is that FTDI may have at some point
switched to a simple common microcontroller based design used between their
various products, and only publicly described the config registers.  The
MiB (Men in Black) might have power to intercept these and reconfigure them
without having to modify the board at all.

So... I wind up in the typical case of having to trust my IC vendors...

Bill
