### ISSUE TITLE
Raspberry Pi Compile Issue

### ISSUE THREAD

**Issue by pfulbrightmii** [waywardgeek/infnoise#92]
sudo make -f Makefile.linux throws the error:

writeentropy.c: In function ‘readNumberFromFile’:
writeentropy.c:29:29: error: comparison is always true due to limited range of data type [-Werror=type-limits]

**Comment by pfulbrightmii** [comment]
Fixed: like 28 of writeentropy.c, change:

char c;

to:

signed char c;

**Comment by SciaticNerd** [comment]
Thank you so much!!! This made everything work fine. I kept getting this error when it should be a simple compile command! (Maybe you were trying to follow the same tutorial/blog post? I officially owe you a beverage.

**Comment by zhaofengli** [comment]
Fixed by https://github.com/leetronics/infnoise/pull/27

**Comment by manuel-domke** [comment]
leetronics #27 has meanwhile been merged into master, so the issue should be fixed.
