### ISSUE TITLE
GPG Keys Expired

### ISSUE THREAD

**Issue by Viajaz** [waywardgeek/infnoise#95]
The following GPG keys have expired:

- https://files.13-37.org/0x4E730A3C.asc as referenced by https://leetronics.de/en/keys/
- https://13-37.org/files/pubkey.gpg  as referenced by https://github.com/waywardgeek/infnoise/blob/master/software/README.md

This is breaking the http://repo.13-37.org APT repository due to `EXPKEYSIG`.

**Comment by manuel-domke** [comment]
GPG Key Expiry has been extended until 2033...
